version: '3'
services:
  customer-service-db:
    container_name: customer-service-db
    image: postgres:14.3-alpine
    volumes:
      - customer-service-db-volume:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=123a456B
      - POSTGRES_DB=customer_db
      - PGDATA=/var/lib/postgresql/data/pgdata
  customer-service:
    depends_on:
      - customer-service-db
    build:
      context: ./application
    container_name: customer-service
    ports:
      - "8090:8090"
volumes:
  customer-service-db-volume:
    driver: local
