global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'customer_service'
    metrics_path: 'actuator/prometheus'
    static_configs:
      - targets: ['customer-service:8090']
        labels:
          application: 'Customer Serivce Application'
          